### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by Zelenya**
Update packages

### CODE REVIEW

**Comment by hdgarrood** [comment]
Could you please remove the changes where only the patch level component of any version range differs? They will only tighten lower bounds and I don’t think they are necessary.

**Comment by Zelenya** [comment]
Done (if I understood it correctly, or `4.1.0` should be `4.0.0` as well?)

**Comment by hdgarrood** [comment]
Oh yeah, come to think of it we should leave the minor level changes alone too, unless we are relying on something introduced in eg v4.1.0 of purescript-nullable.

**Comment by Zelenya** [comment]
Anything else I should do?

**Comment by hdgarrood** [comment]
Sorry for the delay. Nothing else you need to do, thanks!

**Pull request merged**
