### PR TITLE
feat(#28): add support for server.address()

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by srghma** [comment]
@garyb @hdgarrood ping...

**Comment by srghma** [comment]
I dont want to be pesky, but this pr is an exact copy of a function from https://github.com/purescript-node/purescript-node-net/blob/1fd91c872ecff202ae86b848f2c8d054f7a751f3/src/Node/Net/Server.purs#L72-L88

I hope this simplifies review, I have already tested it in my fork of hyper https://github.com/purescript-hyper/hyper/pull/94

**Comment by srghma** [comment]
@hdgarrood updated

but it's also possible to implement this without duplicating the code

```
... -- export address from here and Address from Net

address = unsafeCoerce Net.adress
```

but `Server` is different, so it's better to duplicate the code

**Comment by hdgarrood** [comment]
Thanks, we will try to get to this after v0.14.0 is released.

**Comment by JordanMartinez** [comment]
Superceded by #49.

**Pull request closed without merging**
